import type { Metadata } from 'next'
import { Providers } from './providers'
import StyledComponentsRegistry from 'lib/registry'

export const metadata: Metadata = {
  title: 'Boilerplate',
  description: 'Generated by Rafael Tavares'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <Providers>{children}</Providers>
        </StyledComponentsRegistry>
      </body>
    </html>
  )
}
